---
title: "PabloJS"
format: html
---

```{r}

library(tidyverse)
library(ggplot2)
library(rnaturalearth)
library(rnaturalearthdata)
library(dplyr)
library(sf)

democracy_data <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2024/2024-11-05/democracy_data.csv')
```

```{r}
commonwealth <- democracy_data |>
  filter(is_commonwealth == TRUE)

commonwealth_1950 <- commonwealth |>
  filter(year == 1950)

commonwealth_2020 <- commonwealth |>
  filter(year == 2020)
```

# Distribution of regime and Electoral categories

```{r}
table(commonwealth_1950$electoral_category)
table(commonwealth_2020$electoral_category)

table(commonwealth_1950$regime_category)
table(commonwealth_2020$regime_category)

```

# EDA Smart analysis

```{r}

install.packages("devtools")
devtools::install_github("daya6489/SmartEDA",ref = "develop")

install.packages("SmartEDA")
install.packages("ISLR")
library("ISLR")
library("SmartEDA")

Carseats= ISLR::Carseats
```
# Overview of the Data

```{r}
ExpData(data=democracy_data,type=1)
```

```{r}
ExpData(data=democracy_data,type=2)
```
# SUmmary of Numerical Variables

```{r}
## Summary statistics by – overall
    ExpNumStat(democracy_data,by="A",gp=NULL,Qnt=seq(0,1,0.1),MesofShape=2,Outlier=TRUE,round=2)
```
```{r}
## Frequency or custom tables for categorical variables
    ExpCTable(democracy_data,Target=NULL,margin=1,clim=10,nlim=5,round=2,bin=NULL,per=T)
    ExpCTable(democracy_data,Target="Price",margin=1,clim=10,nlim=NULL,round=2,bin=4,per=F)
    ExpCTable(democracy_data,Target="Urban",margin=1,clim=10,nlim=NULL,round=2,bin=NULL,per=F)    

## Summary statistics of categorical variables
    ExpCatStat(democracy_data,Target="Urban",result = "Stat",clim=10,nlim=5,Pclass="Yes")
## Inforamtion value and Odds value
    ExpCatStat(Carseats,Target="Urban",result = "IV",clim=10,nlim=5,Pclass="Yes")
```


# How are the democratic trends in common wealth countries?

# How these ones might variate from region to region?
