---
title: "PabloJS"
format: html
---

Nine essential characteristics of great teamwork 

https://www.wework.com/ideas/professional-development/management-leadership/nine-characteristics-of-great-teamwork

A team’s success is highly dependent upon the participation of all its members, as the final product must showcase everyone's work and learning. All this is subject to the team's communication and interaction in the working process. Although there are many factors that influence this, these are some 9 essential characteristics in a team:

- Great and constant communication: Typically throughout the work, this is a way to demonstrate care for each other and the project itself.

- Individual Talent: Which involves the active commitment of its members to give as much as they can to the team.

- Sense of Belongingness: This is important to make everyone feel welcomed in the workspace.

- Strong Leadership: knowing that each member has as much saying as all of the other members.

- Clear Structure: Specially in teamworks like the ones that we are doing, it is helpful to have a constant idea of what we are doing in each stage of the project.

- Reachable goals: Knowing and setting what we want to achieve from the strat helps the team on balancing the amount of time and effort that they should put into each task.

- Constructive Feedback: Knowing how to deliver feedback is helpful specially in avoiding misunderstandings while also demonstrating respect for eachothers work.

- Positive Atitude: Even on times of stress, a positive attitude can enhance the working environment of a group by remembering that there is more beyond the working part of the project.

- Focusing on solutions: In times of troubles, focusing thinking each other as a team against the deadlines is fundamental to maintain a sense of social responsibility.
